Enable BruControl
universam1/iSpindel pull request #428
Opened 2020-10-25 23:12 UTC by BrunDog

Hi, this PR is to enable iSpindel data exchange to BruControl (brewing automation software - brucontrol.com)

2020-11-10 16:42 UTC, thegreatgunbantoad commented
May C++ could be better.  Can this:
>     strcpy(global_name, my_name);
>     strcat(global_name, "_g");
>     sender.add("Name", global_name, 0);
>     sender.add("Value", Gravity, 0);

Be simplified to this, avoiding the need for a temporary variable?
>    sender.add("Name", my_name+"_g", 0);
>    sender.add("Value", Gravity, 0);

Also is there a reason that Name and Value are capitalised, this isn't in keeping with the rest of the code.

2020-11-10 17:07 UTC, BrunDog commented
Thanks for reviewing! I don't think you can just add null terminated chars, but maybe I'm wrong. 'Name' and 'Value' are capitalized because that the the field name expected by BruControl (the receiving application).

2020-11-10 20:27 UTC, thegreatgunbantoad commented
Cool, always handy to learn new stuff.

2020-11-10 23:33 UTC, thegreatgunbantoad commented
I cannot get my noggin around how C++ handles character arrays / strings with so little ability to translate between the two.  I like a heavily typed language but that assumes it contains type casts.  I cant see how you type cast between strings and char arrays at all.

2020-12-27 00:46 UTC, thegreatgunbantoad commented
Using 
sender.add("Name", String(my_name) +"_g", 0);
Looks to be allowable in the compiler.  But as I said my C++ is a bit poo.

2021-01-11 18:09 UTC, BrunDog commented
Hi @universam1. Wondering the review cycle planning for this PR?

2021-03-26 11:20 UTC, MarcoCLA commented on pio/lib/WiFiManagerKT/WiFiManagerKT.h
> +{"name":"BruControl", "token":0,"server":1,"url":1,"port":1,"channel":0,"db":0,"username":0,"password":0,"job":0,"instance":0}];
url->uri

2021-06-01 23:38 UTC, BrunDog reviewed
Please complete the pull request. Conflicts resolved.

2021-06-05 11:41 UTC, exoticatom commented
It would be great if this is finally resolved. Many of us are waiting for BruControl to be part of releases. 

Thanks!

2021-06-05 12:34 UTC, universam1 requested changes
please rebase on latest changes and adjust API usage

2021-06-05 20:45 UTC, BrunDog commented
> please rebase on latest changes and adjust API usage

Sorry, I don't know what this means. Can you please clarify?

2021-08-12 00:25 UTC, closed without merging